export const types = {
  steel: ['#9EB7B8', 'black'],
  fighting: ['#D56723', 'white'],
  dragon: ['#53A4CF', '#F16E57', 'white'],
  water: ['#4592C4', 'white'],
  fire: ['#FD7D24', 'white'],
  electric: ['#EED535', 'black'],
  fairy: ['#FDB9E9', 'black'],
  ice: ['#51C4E7', 'black'],
  bug: ['#729F3F', 'white'],
  normal: ['#A4ACAF', 'black'],
  grass: ['#9BCC50', 'black'],
  poison: ['#B97FC9', 'white'],
  psychic: ['#F366B9', 'white'],
  rock: ['#A38C21', 'white'],
  ground: ['#F7DE3F', '#AB9842', 'black'],
  ghost: ['#7B62A3', 'white'],
  dark: ['#707070', 'white'],
  flying: ['#3DC7EF', '#BDB9B8', 'black'],
};

export const typeWeaknesses = {
  steel: ['fire', 'fighting', 'ground'],
  fighting: ['flying', 'psychic', 'fairy'],
  dragon: ['ice', 'dragon', 'fairy'],
  water: ['electric', 'grass'],
  fire: ['water', 'ground', 'rock'],
  electric: ['ground'],
  fairy: ['poison', 'steel'],
  ice: ['fire', 'fighting', 'rock', 'steel'],
  bug: ['fire', 'flying', 'rock'],
  normal: ['fighting'],
  grass: ['fire', 'ice', 'poison', 'bug'],
  poison: ['ground', 'psychic'],
  psychic: ['bug', 'ghost', 'dark'],
  rock: ['water', 'grass', 'fighting', 'ground', 'steel'],
  ground: ['water', 'grass', 'ice'],
  ghost: ['ghost', 'dark'],
  dark: ['fighting', 'bug', 'fairy'],
  flying: ['electric', 'ice', 'rock'],
};
